spring:
  application:
    name: budzet

  datasource:
    url: jdbc:mysql://localhost:3306/budzet?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/local-data.sql

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

custom:
  jwt:
    secret-pattern: ${JWT_SECRET}
    expire-millis: "#{1000L * 60 * 60}"
